name: check_that_pushes_to_the_master_branch_is_from_develop
on:
 pull_request:
    branches: [ "master" ]

jobs:
  check-if-source-branch-is-develop:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Exit if the branch is not develop
      run: |
        if [[ "${{ github.ref }}" != "refs/heads/develop" ]]; then
          echo "Branch is not develop, exiting and failing the job."
          exit 1
        fi

    - name: branch-is-develop
      run: echo "job is successful" 
    
                             
