name: check_that_pushes_to_the_master_branch_is_from_develop
on: [workflow_dispatch]

jobs:
    build:
      name: Run Script
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - uses: Amadevus/pwsh-script@v2
          with:
           script: |
                   $sourceBranch = "$(System.PullRequest.SourceBranch)"

                   if($sourceBranch -ne "refs/heads/develop")
                   {
                     exit 1
                             }
