name: Build AppWish Ollama with Make

on:
  pull_request:
    branches: [ "develop" ]
  push:
    branches: [ "master" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '19'
          cache: 'maven'
    
      - name: checkout repo
        uses: actions/checkout@main
     
      - name: build 
        run: make appwish
      
