name: Makefile CI for the develop branch

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
    
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
      - name: checkout repo
        uses: actions/checkout@main
        
      - uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
      
      - name: build code-generator
        run: make code-generator
        
      - name: build appwish-gui
        run: make appwish
      
    



          

          
