name: Makefile CI for the master branch (Security check)

on:
  pull_request:
    branches: [ "master" ]

jobs:

  security-code_generator:
    runs-on: ubuntu-latest
    steps:
      - uses: snyk/actions/setup@master
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities in code-generator-ollama
        working-directory: cg/CodeGenerator/CodeGenerator
        run: snyk test
        continue-on-error: false
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}


  security-appwish:
    runs-on: ubuntu-latest
    steps:
      - uses: snyk/actions/setup@master
      - uses: actions/checkout@master
     
      - name: build dependency requirement for code-generator-ollama-gui
        run: make code-generator
      
      - name: Run Snyk to check for vulnerabilities in code-generator-ollama-gui
        working-directory: AppWish/AppWish
        run: snyk test
        continue-on-error: false
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

        



          

          
