name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
      - name: checkout repo
        uses: actions/checkout@main
        
      - name: build code-generator
        run: make code-generator
        
      - name: build appwish-gui
        run: make appwish
      
    
  security-code_generator:
    runs-on: ubuntu-latest
    steps:
      - uses: snyk/actions/setup@master
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities in code-generator-ollama
        working-directory: cg/CodeGenerator/CodeGenerator
        run: snyk test
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  security-appWish:
    runs-on: ubuntu-latest
    steps:
      - uses: snyk/actions/setup@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Snyk to check for vulnerabilities in code-generator-gui-ollama
        working-directory: AppWish/AppWish/
        run: snyk test
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          

          
