name: Makefile CI for the develop branch

on:
  pull_request:
    branches: [ "develop" ]
    
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '20'
          cache: 'maven'
    
      - name: checkout repo
        uses: actions/checkout@main
     
      
      - name: build code-generator
        run: make code-generator
        
      - name: build appwish-gui
        run: make appwish
      
    



          

          
