name: SCA Scan AppWish

on:
 workflow_dispatch: 
 

jobs:
  security-code_generator:
    uses: pwgit-create/APPWISH_OLLAMA/.github/workflows/sca_scan_base.yml@main
    with:
       working-path: cg/CodeGenerator/CodeGenerator
       name-of-snyk-step: Check for vulnerabilities in code-generator-ollama
       is-appwish-gui-dependency-needed: false

  security-appwish:
    uses: pwgit-create/APPWISH_OLLAMA/.github/workflows/sca_scan_base.yml@main
    with:
       working-path: AppWish/AppWish
       name-of-snyk-step: Check for vulnerabilities in code-generator-ollama-gui
       is-appwish-gui-dependency-needed: true   
     
     

        



          

          
