name: SCA Scan Base
on:
  workflow_call:
    inputs:
      working-path:
         description: 'The path of the pom.xml'
         required: true
         type: string
        
      name-of-snyk-step:     
         description: 'The name of the job that executes the snyk action'
         required: true
         type: string
      
jobs:
 snyk-action:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v4
  - uses: actions/setup-java@v4
    with:
      distribution: 'temurin'
      java-version: '19'
      cache: 'maven'
  
  - name: checkout repo
    uses: actions/checkout@main
  
  - name: build appwish-ollama
    run: make appwish    
  - uses: snyk/actions/setup@master
  - uses: actions/checkout@master
  
  - name: ${{inputs.name-of-snyk-test}}
    id: snyk-test
    working-directory: ${{inputs.working-path}}
    run: snyk test
    continue-on-error: false
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    
