name: Snyk Reusable Workflow

on:
  workflow_call:
    inputs:
      snyk-name:
        required: true
        type: string
      snyk-working-path:
        required: true
        type: string

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: snyk/actions/setup@master
      - uses: actions/checkout@master
      - name: ${{ inputs.snyk-name}}
        working-directory: ${{ inputs.snyk-working-path}}
        run: snyk test
        continue-on-error: false
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}







