name: Verify that merges to Master come from develop

on:
  push:
    branches: [ "develop" ]
 

jobs:
  veryify-that-origion-branch-is-develop:
   runs-on: ubuntu-latest
   steps:
     - name: print job information
       run: echo "Merges to master must have develop as the origin branch"
  
